import type { Metadata } from "next";
import "@/styles/globals.css";

import { Navbar } from "@/components/layout/navbar";

import { geistMono, neueMontreal, suisse } from "@/assets/fonts";

import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Biz Doctor - Your Business Doctor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(geistMono.variable, suisse.className, neueMontreal.variable, "antialiased")}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
