export * from "./about";
export * from "./blogs";
export * from "./contact";
export * from "./faq";
export * from "./hero";
export * from "./services";
export * from "./testimonials";
export * from "./videos";
export * from "./why-choose";
